# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0002_auto_20170809_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processing_fee',
            field=models.IntegerField(default=10000),
        ),
    ]
