# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmi', '0003_product_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='website',
            field=models.URLField(default='http://www.zenithbank.com'),
        ),
    ]
