# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20170630_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='answer',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='help',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
