# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_auto_20170706_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='answer',
            field=models.TextField(),
        ),
    ]
