# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0004_auto_20170706_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='cat',
            field=models.CharField(default='buyer', max_length=200),
        ),
    ]
