# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0005_help_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
