# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0006_help_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
