# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0008_auto_20170720_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='cat',
            field=models.CharField(default='buyer', max_length=200),
        ),
        migrations.AlterField(
            model_name='help',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
