# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0010_remove_help_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='main',
        ),
    ]
