# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('Country', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[(1, b'Land'), (2, b'Houses'), (3, b'Estate')], default='Land', max_length=200)),
                ('status', models.CharField(choices=[(b'rent', b'For Rent'), (b'sale', b'For Sale'), (b'lease', b'For Lease')], default='sale', max_length=200)),
                ('bedroom', models.CharField(max_length=200)),
                ('bathroom', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
            ],
        ),
    ]
