# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[(b'land', b'Land'), (b'house', b'Houses'), (b'estate', b'Estate')], default='Land', max_length=200),
        ),
    ]
