# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20170707_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(default='No 16 Lugbe Federal housing', max_length=200),
        ),
    ]
