# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20170708_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='actual_value',
            field=models.CharField(default='600000', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='discount',
            field=models.CharField(default='0.4', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(default='9.049571450898236 ', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(default='7.484504930393339', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='zipcode',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(default='500000', max_length=200),
        ),
    ]
