# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20170710_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='developer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='property.Developer'),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(default='1', to='property.Feature'),
        ),
    ]
