# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20170710_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=1000)),
                ('featured', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[(b'thumbnail', b'Thumbnail'), (b'real_size', b'Real Size')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='property',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='picture',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
