# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20170710_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='actual_value',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='bed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='developer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='property.Developer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='discount',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(default='', to='property.Feature'),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
