# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20170710_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[(b'appliances', b'Appliances'), (b'interior', b'Interior'), (b'exterior', b'Exterior')], default='', max_length=200),
        ),
    ]
