# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_feature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='header',
            field=models.CharField(choices=[(b'kitchen', b'Kitchen'), (b'laundry', b'Laundry'), (b'garage', b'Garage'), (b'heating', b'Heating')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[(b'interior', b'Inetrior'), (b'exterior', b'Exterior')], default='', max_length=200),
        ),
    ]
