# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20170710_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[(b'interior', b'Inetrior'), (b'exterior', b'Exterior'), (b'neighborhood', b'School And Neighborhood')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='feature',
            name='header',
            field=models.CharField(default='', max_length=200),
        ),
    ]
