# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20170710_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[(b'interior', b'Interior'), (b'exterior', b'Exterior'), (b'neighborhood', b'School And Neighborhood')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='Country',
            field=models.CharField(default='nigeria', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='actual_value',
            field=models.CharField(default='500000', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(default='5000', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.CharField(default='2', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='bed',
            field=models.CharField(default='3', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.CharField(default='2', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(default='"oriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='discount',
            field=models.CharField(default='0.1', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(default='1000000', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='zipcode',
            field=models.CharField(default='234', max_length=200),
        ),
    ]
