# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_property_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='types',
        ),
    ]
