# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20170713_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='projection',
            field=models.CharField(default='3.4', max_length=200),
        ),
    ]
