# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20170714_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(default='1000000', max_length=200),
        ),
    ]
