# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_property_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='trainscore',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='property',
            name='vehicle',
            field=models.IntegerField(default='8'),
        ),
        migrations.AddField(
            model_name='property',
            name='walkscore',
            field=models.IntegerField(default='4'),
        ),
    ]
