# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20170717_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='transdesc',
            field=models.CharField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', max_length=200),
        ),
    ]
