# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_offer_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
