# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20170717_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='down_payt',
            field=models.IntegerField(default=200000),
        ),
    ]
