# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_sale_down_payt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
