# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_auto_20170717_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='state',
            field=models.CharField(choices=[('True', 'True'), ('false', 'False')], default='True', max_length=10),
        ),
    ]
