# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_auto_20170717_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='country',
        ),
    ]
