# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_sale_pptystate'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changefrom', models.IntegerField(default=1000000)),
                ('changeto', models.IntegerField(default=2000000)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=200)),
                ('proeprty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
