# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_auto_20170717_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofbath', models.IntegerField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Cooling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterheater', models.BooleanField()),
                ('ac', models.BooleanField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofkitchen', models.IntegerField()),
                ('noofstove', models.IntegerField()),
                ('eat', models.BooleanField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garagecount', models.IntegerField()),
                ('garagetype', models.CharField(blank=True, max_length=100)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('familyrooms', models.IntegerField()),
                ('diningroom', models.BooleanField()),
                ('diningnumber', models.IntegerField()),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Room'),
        ),
    ]
