# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_auto_20170717_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction', models.CharField(max_length=200)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apperance', models.CharField(max_length=100)),
                ('deck', models.CharField(choices=[('True', 'true'), ('False', 'false')], max_length=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.Property')),
            ],
        ),
    ]
