# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0034_building_exterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='room',
        ),
        migrations.AddField(
            model_name='level',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
        migrations.AlterField(
            model_name='parking',
            name='property',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
    ]
