# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0037_utility'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lotsize',
            field=models.CharField(default='45 x 107', max_length=50),
        ),
    ]
