# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0039_auto_20170720_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='src',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.TextField(default='http://mallorcapropertyhouse.co.uk/wp-content/uploads/2014/10/Beautiful_Luxury_House_with_Swiming_Pool_Wallpapers_for_Desktop.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='transdesc',
            field=models.TextField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry.', max_length=200),
        ),
    ]
