# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_auto_20170720_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='"oriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate "'),
        ),
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.TextField(default='http://mallorcapropertyhouse.co.uk/wp-content/uploads/2014/10/Beautiful_Luxury_House_with_Swiming_Pool_Wallpapers_for_Desktop.jpg'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transdesc',
            field=models.TextField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry.'),
        ),
    ]
