# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0042_auto_20170720_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='developer',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[(b'interior', b'Interior'), (b'exterior', b'Exterior'), (b'neighborhood', b'School And Neighborhood')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='header',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.IntegerField(default=1000000),
        ),
    ]
