# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0043_auto_20170720_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='construction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='developer',
            name='website',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='changeto',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='history',
            name='source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='src',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='picture',
            name='type',
            field=models.CharField(choices=[(b'thumbnail', b'Thumbnail'), (b'real_size', b'Real Size')], max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='Country',
            field=models.CharField(default='nigeria', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='actual_value',
            field=models.CharField(default='500000', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.CharField(default='2', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='bed',
            field=models.CharField(default='3', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.CharField(default='2', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='built',
            field=models.CharField(default='1000', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='community',
            field=models.CharField(default='Rural Tract', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='discount',
            field=models.CharField(default='0.1', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='projection',
            field=models.CharField(default='3.4', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[(b'rent', b'For Rent'), (b'sale', b'For Sale'), (b'lease', b'For Lease')], default='sale', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='stories',
            field=models.CharField(default='5', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.CharField(default='No 16 Lugbe Federal housing', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='style',
            field=models.CharField(default='Traditional Style', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='types',
            field=models.CharField(choices=[(b'land', b'Land'), (b'house', b'Houses'), (b'estate', b'Estate')], default='Land', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='zipcode',
            field=models.CharField(default='234', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='down_payt',
            field=models.IntegerField(default=100000),
        ),
    ]
