# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0045_auto_20170720_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='thumbnail',
        ),
    ]
