# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0046_auto_20170720_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='"oriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate "'),
        ),
        migrations.AddField(
            model_name='property',
            name='thumbnail',
            field=models.TextField(default='http://mallorcapropertyhouse.co.uk/wp-content/uploads/2014/10/Beautiful_Luxury_House_with_Swiming_Pool_Wallpapers_for_Desktop.jpg'),
        ),
    ]
