# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0047_auto_20170720_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('transdesc', models.TextField()),
            ],
        ),
    ]
