# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0048_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(default='2', max_length=200),
        ),
    ]
