# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0051_remove_property_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='refernceid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
