# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0053_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agentname',
            field=models.CharField(default='Funmi Ajayi', max_length=100),
        ),
    ]
