# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0054_property_agentname'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='dollarprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.IntegerField(default=1000000, help_text='Naira value of the property'),
        ),
    ]
